services:
  db:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  server:
    build: ./server
    depends_on:
      - db
    environment:
      DB_URL: postgresql+asyncpg://postgres:example@db:5432/postgres
    ports:
      - "8000:8000"

  client:
    build: ./client
    ports:
      - "3000:80"
